baseURL = "https://renteria.netlify.app"
languageCode = "en-us"
[[menu.main]]
name = "Services"
url = "/services"
weight = 4
[[menu.main]]
name = "Testimonials"
parent = "Resources"
url = "/testimonials"
weight = 2
[[menu.main]]
name = "My Partners"
parent = "Resources"
url = "/partners"
weight = 1
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[[menu.main]]
name = "Resources"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
category = "categories"
project = "projects"
tag = "tags"
