baseURL = "https://completemuscletherapy.net/"
languageCode = "en-us"
[[menu.main]]
name = "Testimonials"
url = "/testimonials"
weight = 5
[[menu.main]]
name = "About Me"
url = "/about"
weight = 2
[[menu.main]]
name = "Services"
url = "/services"
weight = 4
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
