---
label: Page Config
hide_body: true
fields:
- name: contact_page
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Contact Page
- name: about_page
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: About Page
- name: service_page
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Service Page
- name: blog_page
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Blog Page
- name: testimonial_page
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Testimonial Page
pages:
- data/pageconfig.yaml
