---
label: Services
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: search_engine_optimization
  type: include
  config: {}
  template: seo
  label: Search Engine Optimization
- name: url
  type: include
  config: {}
  template: url
  label: URL
pages:
- content/services/deep-tissue-massage.md
- content/services/relaxation-massage.md
