---
label: Services
hide_body: false
fields:
- name: weight
  type: number
  label: Order
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: title
  type: text
  config:
    required: false
  label: Title
- name: featured_image
  type: file
  config:
    maxSize: 64
  label: Featured Image
- name: search_engine_optimization
  type: include
  config: {}
  template: seo
  label: Search Engine Optimization
- name: url
  type: include
  config: {}
  template: url
  label: URL
pages:
- content/services/deep-tissue-massage.md
- content/services/neuromuscular-therapy.md
- content/services/relaxation-massage.md
- content/services/sports-massage.md
- content/services/swedish.md
